### ISSUE TITLE
Raw definitions

### ISSUE THREAD

**Issue by nicklandgrebe** [nicklandgrebe/active-resource.js#13]
## Stories

* As a developer not using Coffeescript, defining classes is awkward, require that I define a class, and then after the fact, call methods on it to define its `className`, `queryName`, and associations.

## Objectives

* Provide a clean interface for raw JS to define classes in a single bundled statement
* FUTURE: Protect methods like `hasMany` from being called whenever
* Add note about `es7.classProperties`

**Comment by ch-tactica** [comment]
Does anybody know the proper way to define a class in ES6?

Currently I have something like:

```
const User = (function() {
    class _User extends Api.Base {
        static initClass() {
            this.className = 'User';
            this.queryName = 'users';
        }
    }

    _User.initClass();
    return _User;
}());

export default User;

```

Which seems to work partially, but I'm running into issues with some functions like `ResourceLibrary.constantize`.

**Comment by nicklandgrebe** [comment]
I can't say one way or another if your class is configured properly.

The one thing I can say is that `ResourceLibrary.constantize` requires that any constant like `User` be defined on the `ResourceLibrary` instance itself.

In your case, that would mean setting `Api.User = (function() { class _User ... })`. The key that you use on `Api` must match `_User.className` static property

**Comment by ch-tactica** [comment]
Thanks for the quick response, looks like the correct ES6 implementation is actually:

```
import Api from './Api';

const _User = (Api.prototype.User = class User extends Api.Base {
  static initClass() {
    this.className = 'User';
    this.queryName = 'users';
  }
});
_User.initClass();

export default _User;
```

**Comment by nicklandgrebe** [comment]
Can now define using

```
ResourceLibrary.createResource(
  class User {
    static define = function() {
      this.hasMany('notifications');
    }
  }
)
```

`className` and `queryName` will be determined based on class name itself, and can be manually overridden in `define`
