### ISSUE TITLE
Cannot get type of the resource

### ISSUE THREAD

**Issue by antonkomarev** [nicklandgrebe/active-resource.js#32]
`type` property is `undefined`:

```js
Project.find('1').then(project => {
    console.log(project.type); // undefined
});
```

I need exactly `type` of the resource returned from the server and not `className` defined in client application.

**Comment by nicklandgrebe** [comment]
Sorry I'm just responding to these now, for some reason my notifications were off. 

`project.klass().queryName` is the closest I can think of. If you get a type back from the server that is supposed to be a Project but doesn't have `type: 'projects'` it won't work anyway

**Comment by drush** [comment]
I agree with @antonkomarev, I think this should be provided.

object.id is available, type is the only other internal attribute that's critical.  If there is a sophisticated STI pattern, users will have to use a 'kind' alias or something similar, but .type should be available regardless.
