### ISSUE TITLE
Getting relations using filtering strategy

### ISSUE THREAD

**Issue by antonkomarev** [nicklandgrebe/active-resource.js#33]
```js
Project.find('1').then(project => {
    project.tasks().all();
});
```
This code produces query: `/projects/1/tasks`

But I need to utilize filters instead:
`/tasks?filter[project][type]=Project&filter[project][id]=1`

Is there is an easy way to do it?

**Comment by nicklandgrebe** [comment]
`project.tasks().where({ project: { type: 'Project', id: '1' }})`

Though why, if you are requesting `/projects/1`, do you need to specify the project id? Or the type for that matter?

**Comment by antonkomarev** [comment]
I don't need to have `/projects/1` in my URI.
My URI: http://localhost/tasks?filter[project][type]=Project&filter[project][id]=1
