### ISSUE TITLE
Wrong endpoint name in production (?)

### ISSUE THREAD

**Issue by CharlieIGG** [nicklandgrebe/active-resource.js#47]
**WHEN** I use this library in development, by declaring
```javascript
const resourceLibrary = createResourceLibrary("http://localhost:3000/api/v2");
```

**THEN** I can call `Car.all()`
**THEN** ActiveResource calls the correct URL: `"http://localhost:3000/api/v2/cars"`

**BUT...**

**WHEN** I use this library in production, by declaring
```javascript
const resourceLibrary = createResourceLibrary("https://mysite.com/api/v2");
```
**THEN** I can call `Car.all()`
**THEN** ActiveResource **INSTEAD** calls an incorrect URL: `"https://mysite.com/api/v2/ts"`

which naturally returns a 404 error.

I honestly don't know where this is coming from.

Any Ideas?

**Comment by CharlieIGG** [comment]
@nicklandgrebe have you seen something like this happen before?

**Comment by nicklandgrebe** [comment]
Can you post your `Car` class?

**Comment by nicklandgrebe** [comment]
https://github.com/nicklandgrebe/active-resource.js#baseclassname

You have to set this property when using a minifier

**Comment by CharlieIGG** [comment]
This does it @nicklandgrebe, I stopped reading after "optional". Just adding Heroku to that sentence would be great for future reference. 👍
