### ISSUE TITLE
how to send raw request

### ISSUE THREAD

**Issue by gadelkareem** [nicklandgrebe/active-resource.js#59]
Is there a way to send a raw request? for ex I used to do something like this with https://github.com/twg/devour:
```
api.runMiddleware({
      url: api.apiUrl + '/users/' + id + '/password',
      method: 'PATCH',
      data,
      model: 'update-password-request'
})
```

**Comment by nicklandgrebe** [comment]
We use `axios`, I suggest just importing that. You can then use the JSONAPI interface to handle your response data and create resources accordingly
